<?php
namespace controllers\crud\viewers;

use Ubiquity\controllers\crud\viewers\ModelViewer;
 /**
  * Class CrudUserViewer
  */
class CrudUserViewer extends ModelViewer{
	//use override/implement Methods

    //DataTable
    public function getCaptions($captions, $className)
    {
        return parent::getCaptions($captions, $className); // TODO: Change the autogenerated stub
    }

    public function getModelDataTable($instances, $model, $totalCount, $page = 1)
    {
        return parent::getModelDataTable($instances, $model, $totalCount, $page); // TODO: Change the autogenerated stub
    }

    public function recordsPerPage($model, $totalCount = 0)
    {
        return parent::recordsPerPage($model, $totalCount); // TODO: Change the autogenerated stub
    }

    protected function getDataTableRowButtons()
    {
        return ['display', 'edit', 'delete'];

    }

    //DataElement
    public function getModelDataElement($instance, $model, $modal)
    {
        return parent::getModelDataElement($instance, $model, $modal); // TODO: Change the autogenerated stub
    }

    public function getElementCaptions($captions, $className, $instance)
    {
        return parent::getElementCaptions($captions, $className, $instance); // TODO: Change the autogenerated stub
    }

    //DataForm
    public function isModal($objects, $model)
    {
    }

    public function getForm($identifier, $instance, $updateUrl = 'updateModel')
    {
    }

    public function getFormCaptions($captions, $className, $instance)
    {
    }


}
