<?php
namespace controllers\crud\datas;

use Ubiquity\controllers\crud\CRUDDatas;
 /**
  * Class CrudUserDatas
  */
class CrudUserDatas extends CRUDDatas{
	//use override/implement Methods

    public function getFieldNames($model)
    {
        return ['Firstname','Lastname','Email', 'suspended', 'groups'];
    }

    public function getFormFieldNames($model, $instance)
    {
        return ['Firstname','Lastname'];
    }

    public function _getInstancesFilter($model)
    {
        return parent::_getInstancesFilter($model); // TODO: Change the autogenerated stub
    }

    public function getManyToManyDatas($fkClass, $instance, $member)
    {
        return parent::getManyToManyDatas($fkClass, $instance, $member); // TODO: Change the autogenerated stub
    }


}
