<?php
namespace controllers\crud\events;

use Ubiquity\controllers\crud\CRUDEvents;
 /**
  * Class CrudUserEvents
  */
class CrudUserEvents extends CRUDEvents{
	//use override/implement Methods
    public function onBeforeUpdateRequest(array &$requestValues, bool $isNew)
    {
        parent::onBeforeUpdateRequest($requestValues, $isNew); // TODO: Change the autogenerated stub
    }

    public function onBeforeUpdate(object $instance, bool $isNew)
    {
        parent::onBeforeUpdate($instance, $isNew); // TODO: Change the autogenerated stub
    }




}
